### PR TITLE
Standalone

### PR DESCRIPTION
**Pull request by macalinao**

### CODE REVIEW

**Comment by macalinao** [comment]
Thats a lot of deletions lol... I'll merge this once it's confirmed that this works.

**Comment by olliestanley** [comment]
It definitely runs, but that's all I know atm

**Comment by macalinao** [comment]
@DziNeIT I have commands working. We need to test. tell me if you are free at any time (and have some sort of test server, i cant find my router ip lol)

**Comment by olliestanley** [comment]
I can't port forward sadly. @simplyianm

**Comment by macalinao** [comment]
hmm I may have to find my router info then. what a pain. oh well it's worth it, we're gonna be famous on bukkit xD

**Comment by olliestanley** [comment]
Pretty much :P

**Comment by olliestanley** [comment]
BTW how are we going to do the objectives API if we want to keep it private for a bit?

**Comment by macalinao** [comment]
We put it in Sam's plugin

**Comment by olliestanley** [comment]
kk

**Comment by olliestanley** [comment]
It took me back a bit to wake up to an email notifying me this had been closed lmao @macalinao

**Pull request closed without merging**
